### ISSUE TITLE
Not showing man page for command I just installed 

### ISSUE THREAD

**Issue by gingerbeardman** [isometry/alfred-man#1]
https://github.com/sveinbjornt/searchfs

`man searchfs` in Alfred only shows `searchfs(2)`

`man searchfs` in Terminal shows `searchfs(1)`

**Comment by isometry** [comment]
The workflow has a rather aggressive caching policy, not expecting the man database to be updated often, and only rebuilding its internal whatis(1) cache once a week (https://github.com/isometry/alfred-man/blob/master/alfredman.py#L19). Assuming Alfred 3, you can force its regeneration by purge the cache with:
```
rm ~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow\ Data/net.isometry.alfred.man/whatis.1.json
```
Please confirm this resolves the issue.

**Comment by gingerbeardman** [comment]
Sadly that does not work.

I can verify that the file has been purged, but it still does not find the man for this command

```
$ man -wa searchfs
/usr/local/share/man/man1/searchfs.1
/usr/share/man/man2/searchfs.2
```

![screen shot 2018-06-07 at 20 58 19](https://user-images.githubusercontent.com/49612/41123157-a56d8e9c-6a95-11e8-8ab8-e96f6cfda310.png)

**Comment by gingerbeardman** [comment]
So I looked at the newly generated json files, and searchfs(1) is not in there either.

Looking at your code, `man -k -Pcat .` does not return it.

```
$ man -k searchfs
searchfs(2)              - search a volume quickly
```

Though other commands in `/usr/local/share/man` are listed for me.

**Comment by isometry** [comment]
Does whatis(1) return it? (`whatis searchfs`)
Any improvement if you force refresh the whatis database? (`sudo /usr/libexec/makewhatis`)

**Comment by gingerbeardman** [comment]
whatis(1) does not. good spot.

no difference using `sudo /usr/libexec/makewhatis` still no result from `whatis` or ``

(I had refreshed `whatis` earlier)

**Comment by gingerbeardman** [comment]
I did `makewhatis -o file.txt` and that does not contain it.

**Comment by isometry** [comment]
What about `/usr/libexec/makewhatis -o /dev/stdout $(cat /etc/manpaths /etc/manpaths.d/*) | fgrep searchfs` ?

Confirm `/usr/local/share/man` is in your `/etc/manpaths` ?

**Comment by gingerbeardman** [comment]
ooh!
```
$ /usr/libexec/makewhatis -o /dev/stdout $(cat /etc/manpaths /etc/manpaths.d/*) | fgrep searchfs
searchfs(1)              - fast filename search on HFS+ and APFS volumes
searchfs(2)              - search a volume quickly
```

/etc/manpaths:
```
/usr/share/man
/usr/local/share/man
```

**Comment by isometry** [comment]
Excellent. I'll aim to update the workflow at the weekend.
Thanks for the bug report. Nice to know someone else finds it useful!

**Comment by gingerbeardman** [comment]
I use it a lot!

**Comment by isometry** [comment]
Could you test the new v2.0 release, here: https://github.com/isometry/alfred-man/releases/tag/v2.0

Thank you.

**Comment by isometry** [comment]
@gingerbeardman : does this new release fix the issue?

**Comment by gingerbeardman** [comment]
Thanks for the prod.

Yes, it does!  Good work. Thanks again
